#include "logic/filter_builder.h"

#include "config.h"

namespace bustaferl {

void buildStreamFilters(StreamFilter (&f)[STREAM_COUNT]) {
  f[STREAM_58A_ATZ] = {RBL_TULL_ATZGERSDORF, LINE_58A, TOWARDS_58A_ATZ};
  f[STREAM_58A_HIETZING] = {RBL_TULL_HIETZING, LINE_58A, TOWARDS_58A_HIETZING};
  f[STREAM_58B_ATZ] = {RBL_ENDEMANN, LINE_58B, FILTER_TOWARDS_58B};
  f[STREAM_U1_LEOPOLDAU] = {RBL_SUEDTIROLER_LEOPOLDAU, LINE_U1,
                            TOWARDS_U1_LEOPOLDAU};
  f[STREAM_U1_OBERLAA] = {RBL_SUEDTIROLER_OBERLAA, LINE_U1, TOWARDS_U1_OBERLAA};
}

void buildScheduleFilters(ScheduleStreamFilter (&f)[STREAM_COUNT]) {
  f[STREAM_58A_ATZ] = {DIVA_TULLNERTALGASSE, LINE_58A, EFA_TOWARDS_58A_ATZ, ""};
  f[STREAM_58A_HIETZING] = {DIVA_TULLNERTALGASSE, LINE_58A,
                            EFA_TOWARDS_58A_HIETZING, ""};
  f[STREAM_58B_ATZ] = {DIVA_ENDEMANNGASSE, LINE_58B, EFA_TOWARDS_58B_ATZ, ""};
  f[STREAM_U1_LEOPOLDAU] = {DIVA_SUEDTIROLER_PLATZ, LINE_U1,
                            EFA_TOWARDS_U1_LEOPOLDAU, ""};
  f[STREAM_U1_OBERLAA] = {DIVA_SUEDTIROLER_PLATZ, LINE_U1,
                          EFA_TOWARDS_U1_OBERLAA, EFA_TOWARDS_U1_OBERLAA_ALT};
}

} // namespace bustaferl
