#!/usr/bin/env python3
"""Render the three fullscreen-state glyphs at 90 px via Pillow + DejaVu, then
emit PBM (P1) files matching what `scripts/pbm-to-progmem.py` expects.

Schritt 0.7 of the v2 migration plan (C9) calls for the three 90 px
fullscreen-error glyphs as 1-bit PROGMEM sprites. We render them by drawing
the Unicode codepoints into a Pillow 1-bit image at the target size — this
gives crisp, faithful raster glyphs without hand-pixeling or building a
fontconvert toolchain (memory feedback-no-tooling-rabbit-holes).

The Pillow dependency is only at *generation* time on the dev host; the
generated PBM/header files are committed, so the ESP32 build has no Python
or Pillow requirement.

Source files written to docs/design_handoff_display/glyph-source/:
    dotted-circle-90.pbm  (U+25CC ◌, Boot screen)
    exclamation-90.pbm    (U+0021 !, Offline screen)
    para-nine-90.pbm      (U+00A7 + '9' = "§9", Auth screen)

Usage:
    scripts/generate-glyph-pbms.py docs/design_handoff_display/glyph-source/
"""

import argparse
import os
import sys

from PIL import Image, ImageDraw, ImageFont

GLYPH_PX = 90

# DejaVu Sans Bold is Debian-default and includes ◌ (U+25CC), §, !, digits.
FONT_PATH = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"


def _render_text(text: str, font_px: int, threshold: int = 128) -> Image.Image:
    """Render `text` centered on a 90x90 canvas; return 1-bit ("1") image.

    Uses Pillow's L-mode + Floyd-Steinberg-free `convert("1", dither=NONE)` to
    get a deterministic 1-bit output. Floyd-Steinberg would add noise that
    blows up the RLE compression budget downstream."""
    img = Image.new("L", (GLYPH_PX, GLYPH_PX), color=0)
    draw = ImageDraw.Draw(img)
    font = ImageFont.truetype(FONT_PATH, size=font_px)

    # Measure the actual bounding box of the rendered glyph(s) and centre.
    bbox = draw.textbbox((0, 0), text, font=font)
    text_w = bbox[2] - bbox[0]
    text_h = bbox[3] - bbox[1]
    # Centre: shift so that the bbox sits centred on the canvas. textbbox
    # returns the glyph's actual ink bbox, including the bbox origin offset
    # — so we subtract the origin (bbox[0], bbox[1]) from the draw position.
    x = (GLYPH_PX - text_w) // 2 - bbox[0]
    y = (GLYPH_PX - text_h) // 2 - bbox[1]
    draw.text((x, y), text, font=font, fill=255)

    # L → 1-bit with hard threshold (no dither).
    return img.point(lambda p, t=threshold: 255 if p >= t else 0).convert(
        "1", dither=Image.Dither.NONE
    )


def _image_to_pbm(img: Image.Image, path: str, title: str) -> None:
    with open(path, "w", encoding="ascii") as f:
        f.write("P1\n")
        f.write(f"# {title}\n")
        f.write("# Generated by scripts/generate-glyph-pbms.py (Pillow + DejaVu Sans Bold)\n")
        f.write(f"{GLYPH_PX} {GLYPH_PX}\n")
        for y in range(GLYPH_PX):
            row = " ".join("1" if img.getpixel((x, y)) else "0" for x in range(GLYPH_PX))
            f.write(row + "\n")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "out_dir",
        help="Output directory for the three PBM files",
    )
    args = parser.parse_args(argv)

    if not os.path.isfile(FONT_PATH):
        print(
            f"generate-glyph-pbms: font not found at {FONT_PATH}; install fonts-dejavu",
            file=sys.stderr,
        )
        return 2

    os.makedirs(args.out_dir, exist_ok=True)

    targets = (
        # (filename, title, text, font_px)
        # ◌ rendered tall — it's a small symbol in most fonts, so push the
        # font size up so the dotted ring fills the canvas.
        (
            "dotted-circle-90.pbm",
            "GLYPH_DOTTED_CIRCLE_90 (Boot screen, U+25CC)",
            "◌",
            120,
        ),
        # ! at native cap-height stays at 90 px easily.
        (
            "exclamation-90.pbm",
            "GLYPH_EXCLAMATION_90 (Offline screen, U+0021)",
            "!",
            96,
        ),
        # §9 — two characters, scale down slightly so both fit horizontally.
        (
            "para-nine-90.pbm",
            "GLYPH_PARA_NINE_90 (Auth screen, U+00A7 + '9')",
            "§9",
            70,
        ),
    )
    for filename, title, text, font_px in targets:
        img = _render_text(text, font_px)
        out = os.path.join(args.out_dir, filename)
        _image_to_pbm(img, out, title)
        print(f"wrote {out}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
