#!/usr/bin/env python3
"""PBM (P1 ASCII) -> C header mit 1-bit Bitmap-Array.

Wird in Schritt 0.7 des v2-Migrationsplans benutzt, um Custom-Glyphs (z.B.
90x90-px Boot/Auth/Offline-Sprites) aus PBM-Source in PROGMEM-faehige
const-Arrays zu konvertieren. Bewusst stdlib-only (kein pip, kein Tooling-
Rabbit-Hole, Memory `feedback-no-tooling-rabbit-holes`).

Usage:
    scripts/pbm-to-progmem.py SOURCE.pbm --name SYMBOL_NAME > OUT.h

PBM-P1-Format (von ImageMagick `-compress none` oder GIMP-Export):

    P1
    # optional comment lines
    <width> <height>
    <bits...>     # ASCII '0' und '1', whitespace beliebig dazwischen

Konvention:
- '1' im PBM = ink (gezeichnetes Pixel)
- Bits werden MSB-first in Bytes gepackt, ein Row-Stride pro Zeile
- Row-Stride = ceil(width / 8) Bytes, Zeilen werden auf Byte-Grenze gepaddet
- Ausgabe: `static const uint8_t NAME[] = { ... };` plus
  `static const uint16_t NAME_W` / `NAME_H` Konstanten
- KEIN PROGMEM-Macro: ESP32 plaziert `const`-Arrays ohnehin in Flash, AVR ist
  out-of-scope.
"""

import argparse
import datetime as _dt
import os
import re
import sys


def _read_pbm_p1(path: str) -> tuple[int, int, list[int]]:
    with open(path, "r", encoding="ascii", errors="strict") as f:
        raw = f.read()

    # Strip line comments (# bis Zeilenende) -> erlaubt PBM-Comments.
    lines = []
    for line in raw.splitlines():
        idx = line.find("#")
        if idx >= 0:
            line = line[:idx]
        lines.append(line)
    cleaned = " ".join(lines).split()

    if not cleaned or cleaned[0] != "P1":
        raise ValueError(f"{path}: erwartet PBM-P1-Magic, gefunden {cleaned[:1]!r}")
    if len(cleaned) < 3:
        raise ValueError(f"{path}: zu kurz fuer P1-Header (width/height fehlen)")

    try:
        width = int(cleaned[1])
        height = int(cleaned[2])
    except ValueError as exc:
        raise ValueError(f"{path}: width/height nicht parsebar: {exc}") from exc

    bit_tokens = cleaned[3:]
    bits: list[int] = []
    for tok in bit_tokens:
        for ch in tok:
            if ch == "0":
                bits.append(0)
            elif ch == "1":
                bits.append(1)
            else:
                raise ValueError(f"{path}: ungueltiges Bit-Zeichen {ch!r}")
    expected = width * height
    if len(bits) != expected:
        raise ValueError(
            f"{path}: erwartet {expected} Bits ({width}x{height}), gefunden {len(bits)}"
        )
    return width, height, bits


def _pack_msb_per_row(width: int, height: int, bits: list[int]) -> bytes:
    row_stride = (width + 7) // 8
    out = bytearray(row_stride * height)
    for y in range(height):
        for x in range(width):
            if bits[y * width + x]:
                byte_idx = y * row_stride + (x >> 3)
                bit_idx = 7 - (x & 7)
                out[byte_idx] |= 1 << bit_idx
    return bytes(out)


_VALID_NAME = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _format_header(name: str, width: int, height: int, src: str, payload: bytes) -> str:
    if not _VALID_NAME.match(name):
        raise ValueError(f"--name {name!r} ist kein gueltiger C-Identifier")
    row_stride = (width + 7) // 8
    today = _dt.date.today().isoformat()

    lines: list[str] = []
    lines.append("// Auto-generated by scripts/pbm-to-progmem.py. DO NOT EDIT.")
    lines.append(f"// Source: {os.path.basename(src)}  Generated: {today}")
    lines.append("//")
    lines.append("// 1-bit bitmap, MSB-first per row, row stride = ceil(w/8) bytes.")
    lines.append("// '1'-Bit = ink. Konsumiere via drawCustomGlyph(canvas, x, y, NAME, w, h).")
    lines.append("")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append(f"static constexpr uint16_t {name}_W = {width};")
    lines.append(f"static constexpr uint16_t {name}_H = {height};")
    lines.append(f"static constexpr uint16_t {name}_STRIDE = {row_stride};")
    lines.append("")
    lines.append(f"static const uint8_t {name}[{len(payload)}] = {{")

    for y in range(height):
        row = payload[y * row_stride : (y + 1) * row_stride]
        hex_bytes = ", ".join(f"0x{b:02X}" for b in row)
        comma = "," if y < height - 1 else ""
        lines.append(f"    {hex_bytes}{comma}  // row {y}")

    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="PBM (P1 ASCII) -> 1-bit C-Header fuer ESP32-Render.",
    )
    parser.add_argument("source", help="Pfad zu einer PBM-P1-Datei")
    parser.add_argument(
        "--name",
        required=True,
        help="C-Identifier fuer das Array (z.B. GLYPH_DOTTED_CIRCLE_90)",
    )
    args = parser.parse_args(argv)

    try:
        width, height, bits = _read_pbm_p1(args.source)
        payload = _pack_msb_per_row(width, height, bits)
        header = _format_header(args.name, width, height, args.source, payload)
    except (OSError, ValueError) as exc:
        print(f"pbm-to-progmem: {exc}", file=sys.stderr)
        return 2

    sys.stdout.write(header)
    return 0


if __name__ == "__main__":
    sys.exit(main())
